# Generated by Django 4.1.3 on 2023-05-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_remove_property_owner_remove_property_property_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('Residence', models.CharField(max_length=50)),
                ('loan_amount', models.IntegerField(blank=True, null=True)),
                ('loan_interest', models.IntegerField(blank=True, null=True)),
                ('loan_value', models.IntegerField(blank=True, null=True)),
                ('loan_balance', models.IntegerField(blank=True, null=True)),
                ('loan_penalty', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
