# Generated by Django 4.1.3 on 2023-05-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_client_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='loan_value',
        ),
        migrations.AddField(
            model_name='client',
            name='loan_collection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
