# Generated by Django 4.1.3 on 2023-07-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_client_lender_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_loan_paid',
            field=models.BooleanField(default=False),
        ),
    ]
