# Generated by Django 4.1.3 on 2023-07-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_loanhistory_loan_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhistory',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanhistory',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
