# Generated by Django 4.1.3 on 2023-07-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_loanhistory_loan_balance_loanhistory_loan_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhistory',
            name='loan_penalty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
